defaultContents = `
{
  "sequences": [
    {
      "sequence": "GGGCCTATAGCTCAGTCGGTTAGAGCAGAGGACTCATAATCCTTTGGTCCACGGTTCGAGTCCGTGTGGGCCCACCA",
      "title": "pseuAeru_MTB_1"
    },
    {
      "sequence": "GGGCCTATAGCTCAGTCGGTTAGAGCAGCGGACTCATAATCCGTTGGTCCACAGTTCGAGTCTGTGTGGGCCCACCA",
      "title": "cinBaum_AC29"
    },
    {
      "sequence": "GGGCCTATAGCTCAACGGTTAGAGCAGAGGACTCATAATCCTTTGGTTCCAGGTTCGAATCCTGGTGGGCCCACCA",
      "title": "antCitr_CITRI_JX5"
    },
    {
      "sequence": "GGGCCCATAGCTCAGTTGGTCAGAGCAGCGGACTCATAATCCGTTGGTCCTAGGTTCAAGTCCTAGTGGGCCCACCA",
      "title": "egiPneu_PARIS"
    },
    {
      "sequence": "GGGCCTATAGCTCAACGGTTAGAGCAGAGGACTCATAATCCTTTGGTTGAAGGTTCGAATCCTTCTGGGCCCACCA",
      "title": "antOryz_PV_ORYZICOLA_BLS256"
    },
    {
      "sequence": "GGGCCTATAGCTCAACGGTTAGAGCAGGGGACTCATAATCCCTTGGTTCCAGGTTCGAATCCTGGTGGGCCCACCA",
      "title": "tenMalt_13637"
    },
    {
      "sequence": "AGGCCTATAGCTCAATAGGTAAGAGCAGAGGACTCATAATCCTTGTGTTGTAGGTTCAAGTCCTACTAGGCCTA",
      "title": "andPort_ALEYRODIDARUM_BT_B_HR_1"
    },
    {
      "sequence": "GGGCCCATAGCTCAGTTGGTTAGAGCAGAGGACTCATAATCCTTTGGTCCACGGTTCGAGTCCGTGTGGGCCCACCA",
      "title": "seuSyri_PV_TOMATO_DC3000"
    },
    {
      "sequence": "GGCGCTTTAGCTCAGCTGGTTAGAGCAGCGGAATCATAATCCGCGTGTCCGGGGTTCGAGTCCCTGAAGCGCCACCA",
      "title": "cidFerr_ATCC53993"
    },
    {
      "sequence": "GGGCCTATAGCTCAATGGTTAGAGCAGAGGACTCATAATCCTTTGGTTCCAGGTTCGAGTCCTGGTGGGCCCACCA",
      "title": "hodDeni_2APBS1"
    },
    {
      "sequence": "GGGCCTATAGCTCAACGGTTAGAGCAGAGGACTCATAATCCTTTGGTTGAAGGTTCGAATCCTGGTGGGCCCACCA",
      "title": "antCitr_CITRI_UI7"
    },
    {
      "sequence": "GGGCCTATAGCTCAGTTGGTTAGAGCAGTGGACTCATAATCCATTTGTCCAAGGTTCAAGTCCTTGTAGGCCCACCA",
      "title": "yclZanc_7_ME"
    },
    {
      "sequence": "GGCGCTTTAGCTCAGTCGGTTAGAGCAGCGGAATCATAATCCGCGTGTCCGGGGTTCGAGTCCCTGAAGCGCCACCA",
      "title": "cidCald_ATCC51756"
    },
    {
      "sequence": "GGCTCTGTAGCTTAAAGGTAAAGCAGCCGACTCATAATCGGGGGATTTCTGGTTCGAACCCAGATGGAGCCACCA",
      "title": "ersKris_ATCC33639"
    },
    {
      "sequence": "GGGTTTATAACTCAATGGTTAGAGTAGAGGACTCATAATTCTTTAGTTGTAGGTTCGACTCCTACTAAACCCA",
      "title": "andCars_RUDDII_PV"
    },
    {
      "sequence": "GGGCCTGTAGCTCAATGGTCAGAGCAGGAGACTCATAATCTCTTGGTTGCAGGTTCGAGTCCTGCCGGGCCCACCA",
      "title": "hioNitr_DSM14787"
    },
    {
      "sequence": "GGGCCTATAGCTCAGCGGTTAGAGCAGGAGACTCATAATCTCTTGGTCCCAGGTTCGAATCCTGGTGGGCCCACCA",
      "title": "ndoOf_UNIDENTIFIED_SCALY_SNA"
    },
    {
      "sequence": "GAGCCCATAGCTCAATGGGTCAGAGCAGCGGATTCATAATCCGATGACCCAGGTTCGAATCCTGGTGGGCTCGCCA",
      "title": "egiFall_LLAP_10"
    },
    {
      "sequence": "GGGCCGGTAGCATAACGGTTAATGCAGCGGCCTCATAAGCCGTTGAGTGCGGGTTCGAATCCCGCCCGGCCCACCA",
      "title": "seuStut_19SMN4"
    },
    {
      "sequence": "GGGCCCATAGCTCAATGGTCAGAGCAGAGGACTCATAATCCTTTGGTTCCAGGTTCGAATCCTGGTGGGCCCACCA",
      "title": "pirSp_UAH_SP71"
    },
    {
      "sequence": "GGGCCCGTAGCTCAATGGTTAGAGCAGAGGACTCATAATCCTTTGGTTCCAGGTTCGAATCCTGGCGGGCCCACCA",
      "title": "pirSali_M19_40"
    },
    {
      "sequence": "GGGCCTGTAGCTCAATGGTTAGAGCAGGAGACTCATAATCTCTTGGTTGCAGGTTCGAGTCCTGCCGGGCCCACCA",
      "title": "hioThio_ARH_4"
    },
    {
      "sequence": "CGTTTGATAGCTCATACGGTAGAGCAGTTGACTCATAATCAATGGGTAACGGGTTCGAATCCCGTTCAAACATCCA",
      "title": "ynuSuns_YC6258"
    },
    {
      "sequence": "GGGCCTATAGCTCAATTGGTTAGAGCAGCGGACTCATAATCCGTTGGTTCCAGGTTCAAGTCCTGGTGGGCCCACCA",
      "title": "lcaDies_B5"
    },
    {
      "sequence": "GGGCCTATAGCTCAACTGGTTAGAGCAGCAGACTCATAATCTGTTGGTTCCAGGTTCAAGTCCTGGTGGGCCCACCA",
      "title": "hioSp_K90MIX"
    },
    {
      "sequence": "GCACCAGTAGCTCAACGGTAGAGCAGGCAACTCATAATTGCTTGGTTATGGGTTCGAATCCCGTCTCGGTGCACCA",
      "title": "rovStua_MRSN_2154"
    },
    {
      "sequence": "GGGCCTATAGCTCAATGGTCAGAGCAGAGGACTCATAATCCTTTGGTTCCAGGTTCGAGTCCTGGTGGGCCCACCA",
      "title": "ratAura_DSM6220"
    },
    {
      "sequence": "GGCTCTCAAGTCGCTTTTTTGCTGGCAGAGCATCGCACTCATAATGCGAGGGTCCCCTGTTCGAGTCAGGGCATAGCCACCA",
      "title": "lloVino_DSM180"
    },
    {
      "sequence": "GGGCCTATAGCTCAACGGTTAGAGCAGGGGACTCATAATCCCTTGGTTGAAGGTTCGAATCCTTCTGGGCCCACCA",
      "title": "yelJian_SBZ_3_12"
    }
  ],
  "annotations": [
    {
      "label": "1",
      "startCharIndex": 30,
      "length": 2
    }
  ]
}
`